apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pac-prune-test-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  pipelineSpec:
    tasks:
      - name: hello
        taskSpec:
          steps:
            - name: test
              image: registry.access.redhat.com/ubi9/ubi-minimal
              script: |
                echo "Testing PAC pruning"
